(function () {
  var KEY = 'munjez-lang';
  var lang = localStorage.getItem(KEY) || 'en';

  var T = {
    en: {
      /* ── Shared ── */
      'back': 'Back to home',
      '404-title': 'Page Not Found',
      '404-desc': "The page you're looking for doesn't exist or has been moved.",
      '404-btn': 'Back to Home',
      /* ── Changelog ── */
      'cl-title': 'Change<span>log</span>',
      'cl-desc': 'A history of updates, new features, and improvements in Munjez.',
      'cl-footer': 'For the complete list of releases and downloads, visit <a href="https://github.com/Osama2214/munjez-releases/releases" target="_blank" rel="noopener noreferrer">GitHub Releases</a>.',
      'back': 'Back to home',
      'contact-support': 'Contact Support',
      'support-cta': 'Still having trouble? Our support team is here to help.',
      /* ── Main nav ── */
      'nav-features': 'Features',
      'nav-screenshots': 'Screenshots',
      'nav-themes': 'Themes',
      'nav-support': 'Support',
      'nav-download': 'Download',
      'nav-developer': 'Developer',
      'nav-dl': '',
      /* ── Hero ── */
      'hero-badge': 'Free App for Windows, Linux & Android',
      'hero-sub': 'Your Ultimate Productivity App',
      'hero-tagline': 'Tasks, habits, focus sessions, notes, whiteboard, and desktop widgets — all in one <strong>beautiful, offline-first</strong> desktop app. Built for people who want to get things done.',
      'hero-win': 'Windows',
      'hero-linux': 'Linux',
      'hero-android': 'Android',
      'win-store': 'Microsoft Store',
      'win-direct': 'Direct Download',
      'android-apk': 'Download APK',
      'android-gplay': 'Google Play',
      'coming-soon': '(Soon)',
      'linux-download': 'Download',
      'linux-guide': 'Install Guide',
      'feat-show-more': 'Show more',
      /* ── Features ── */
      'feat-label': 'Features',
      'feat-title': 'Everything you need<br>to stay productive',
      'feat-desc': '12 powerful tools packed into one fast, beautiful desktop app — from tasks and habits to notes, whiteboard, and floating widgets.',
      'feat-tasks-title': 'Smart Task Management',
      'feat-tasks-desc': 'Organize tasks into folders with priorities and due dates. Set recurring tasks, attach voice notes, files, and images — every detail covered.',
      'feat-cal-title': 'Calendar Integration',
      'feat-cal-desc': 'View your tasks in Year, Month, Week, and Day views. Full Hijri calendar support with drag-and-drop task scheduling across dates.',
      'feat-focus-title': 'Focus Mode (Pomodoro)',
      'feat-focus-desc': 'Stay productive with timed focus sessions and breaks. Color-coded phases keep you in the right mindset — red for focus, green for short breaks, orange for long breaks.',
      'feat-habits-title': 'Habit Tracker',
      'feat-habits-desc': 'Build and maintain daily habits with visual streak tracking. Log each habit every day and watch your consistency grow over time.',
      'feat-stopwatch-title': 'Stopwatch',
      'feat-stopwatch-desc': 'Time anything with precision. Record laps, track splits, and stay on top of your sessions with a clean, distraction-free interface.',
      'feat-sounds-title': 'White Noise & Sounds',
      'feat-sounds-desc': 'Block out distractions with a library of ambient sounds. Mix rain, café, nature, and more to create your perfect focus environment.',
      /* ── Feature tags ── */
      'tag-folders': 'Folders', 'tag-priorities': 'Priorities', 'tag-recurring': 'Recurring Tasks',
      'tag-voice-notes': 'Voice Notes', 'tag-recycle-bin': 'Recycle Bin',
      'tag-4views': '4 Views', 'tag-hijri': 'Hijri Calendar', 'tag-drag-drop': 'Drag & Drop',
      'tag-pomodoro': 'Pomodoro Timer', 'tag-color-phases': 'Color Phases', 'tag-flip-clock': 'Flip Clock Widget',
      'tag-daily-streaks': 'Daily Streaks', 'tag-streak-cal': 'Streak Calendar', 'tag-color-tags': 'Color Tags',
      'tag-lap-times': 'Lap Times', 'tag-milliseconds': 'Milliseconds',
      'tag-rain': 'Rain', 'tag-cafe-noise': 'Café Noise', 'tag-nature': 'Nature Sounds', 'tag-volume-mix': 'Volume Mix',
      /* ── New feature cards ── */
      'feat-notes-title': 'Notes',
      'feat-notes-desc': 'A rich text editor for your thoughts. Organize notes in grid, list, or split view with images, voice recordings, and color-coded cards.',
      'feat-memories-title': 'Memories & Journal',
      'feat-memories-desc': 'Capture life moments with photo-based journaling. Tag, search, and revisit your memories organized by date with time elapsed tracking.',
      'feat-whiteboard-title': 'Whiteboard',
      'feat-whiteboard-desc': 'Draw, diagram, and brainstorm on an infinite canvas. Collaborate in real-time with others through live multi-user editing.',
      'feat-countdown-title': 'Countdown Timer',
      'feat-countdown-desc': 'Set countdowns for deadlines, events, or goals. Manage multiple timers at once with visual progress cards and audio alerts.',
      'feat-sync-title': 'Cloud Sync',
      'feat-sync-desc': 'Sign in with Google or email to sync your data across devices via Firebase. Your tasks, habits, notes, and more stay in sync — securely and in real time.',
      'feat-widgets-title': 'Desktop Widgets',
      'feat-widgets-desc': 'Pin floating widgets on your desktop — focus timer, tasks, habits, calendar, countdowns, and more. Always visible, always on top.',
      'tag-rich-editor': 'Rich Editor', 'tag-grid-view': 'Grid View', 'tag-voice-recordings': 'Voice Recordings', 'tag-tags': 'Tags',
      'tag-photo-journal': 'Photo Journal', 'tag-date-tracking': 'Date Tracking', 'tag-search': 'Search',
      'tag-drawing': 'Drawing', 'tag-collaboration': 'Real-time Collaboration', 'tag-diagrams': 'Diagrams',
      'tag-cross-device': 'Cross-Device', 'tag-firebase': 'Firebase', 'tag-realtime-sync': 'Real-time', 'tag-optional': 'Optional',
      'tag-multiple-timers': 'Multiple Timers', 'tag-audio-alerts': 'Audio Alerts', 'tag-progress-cards': 'Progress Cards',
      'tag-floating': 'Floating', 'tag-always-on-top': 'Always on Top', 'tag-11-widgets': '11+ Widgets',
      /* ── Screenshots ── */
      'ss-label': 'Screenshots',
      'ss-title': 'See it in action',
      'ss-desc': 'Explore every feature through real screenshots of the app.',
      'tab-tasks': 'Tasks',
      'tab-cal': 'Calendar',
      'tab-habits': 'Habits',
      'tab-focus': 'Focus',
      'tab-stopwatch': 'Stopwatch',
      'tab-notes': 'Notes',
      'tab-memories': 'Memories',
      'tab-whiteboard': 'Whiteboard',
      'tab-countdown': 'Countdown',
      'tab-widgets': 'Widgets',
      /* ── Focus section ── */
      'focus-label': 'Focus Mode',
      'focus-title': 'Every phase has<br>its own energy',
      'focus-desc': 'Color-coded Pomodoro sessions that put you in the right mindset for every moment of your work day.',
      'focus-time': 'Focus Time',
      'focus-time-desc': 'Deep work mode — stay locked in',
      'short-break': 'Short Break',
      'short-break-desc': 'Quick reset — step away from the screen',
      'long-break': 'Long Break',
      'long-break-desc': "You've earned it — recharge fully",
      /* ── Themes ── */
      'themes-label': 'Themes',
      'themes-title': 'Make it yours',
      'themes-desc': 'Switch between beautiful color themes to match your mood and workflow.',
      /* ── Support (home) ── */
      'sup-label': 'Support',
      'sup-title': "Need help?<br>We've got you",
      'sup-desc': 'Report issues, ask for features, or reach out for help getting Munjez running smoothly.',
      'sup-main-title': 'Get help from the Munjez team',
      'sup-main-desc': 'If you hit a bug or have a feature suggestion that can make Munjez better, open a ticket on GitHub and include a screenshot when possible. We review issues regularly and prioritize fixes based on impact.',
      'sup-btn-bug': 'Report a bug',
      'sup-btn-issues': 'View all issues',
      'sup-btn-email': 'Email support',
      'sup-more': 'Open full Support Center',
      'sup-tips-title': 'Before reporting, remember',
      'sup-tip1': '<strong>Update first:</strong> install the latest release and retry the issue.',
      'sup-tip2': '<strong>Share context:</strong> include your OS version and what you were doing.',
      'sup-tip3': '<strong>Add media:</strong> attach a screenshot or short clip for faster troubleshooting.',
      /* ── Download (home) ── */
      'dl-label': 'Download',
      'dl-title': 'Ready to get<br><span>things done?</span>',
      'dl-desc': 'Free, fast, and completely offline. No account. No subscription. Just you and your goals.',
      'dl-win': 'Windows',
      'dl-win-sub': 'Microsoft Store',
      'dl-linux': 'Linux',
      'dl-linux-sub': 'AppImage · DEB · RPM',
      'dl-android': 'Android',
      'dl-android-sub': 'APK Download',
      'dl-no-account': 'No account needed',
      'dl-offline': 'Works offline',
      'dl-free': 'Free forever',
      'dl-count-label': 'downloads so far',
      /* ── Footer ── */
      'footer-privacy': 'Privacy Policy',
      'footer-support': 'Support Center',
      'footer-changelog': 'Changelog',
      'dev-label': 'Meet the Developer',
      'dev-name': 'Osama Ahmed',
      'dev-role': 'Developer & Creator of Munjez',
      'dev-bio': 'Passionate about building tools that help people get things done. Munjez started as a personal project and grew into a full productivity suite — designed, built, and maintained by one developer.',
      /* ── Windows install ── */
      'win-dl-started': 'Your download has started!',
      'win-hero-title': 'Installing <span>Munjez</span> on Windows',
      'win-hero-desc': "If your browser didn't start the download, click the button below. Once downloaded, run the installer.",
      'win-dl-btn': 'Download again',
      'win-warn': "If Windows shows a security warning — here's how to handle it",
      'win-sc1': 'Browser blocked the download',
      'win-sc2': 'SmartScreen warning appears',
      'win-sc3': "File blocked — can't run at all",
      'win-sc1-s1': 'In <strong>Chrome</strong>: open the downloads bar → click <strong>⋮</strong> next to the file → <strong>Keep</strong>',
      'win-sc1-s2': 'A second prompt appears — click <strong>Keep anyway</strong>',
      'win-sc1-s3': 'In <strong>Edge</strong>: click <strong>...</strong> → <strong>Keep</strong> → <strong>Show more</strong> → <strong>Keep anyway</strong>',
      'win-sc1-s4': 'Run the installer — Windows may then show a SmartScreen warning, follow <strong>Scenario 2</strong> below',
      'win-sc2-s1': 'Click <strong>More info</strong>',
      'win-sc2-s2': 'Click <strong>Run anyway</strong>',
      'win-sc3-s1': 'Right-click the file → click <strong>Show more options</strong>',
      'win-sc3-s2': 'Click <strong>Properties</strong>',
      'win-sc3-s3': 'Check <strong>Unblock</strong> → click <strong>OK</strong>',
      'win-sc3-s4': 'Run the installer again',
      /* ── Linux install ── */
      'lx-title-pre': 'Installing',
      'lx-title-mid': 'on Linux —',
      'lx-dl-started': 'Your download has started!',
      'lx-hero-desc': "If your browser didn't start the download, click the button below.",
      'lx-dl-btn': 'Download again',
      'lx-hint1': 'Download the file using the button above',
      'lx-hint2': 'Right-click the download folder → <span>Open Terminal Here</span>',
      'lx-hint3': 'Run the installation command below',
      'lx-install': 'Installation',
      'lx-trouble': 'Troubleshooting',
      /* ── Linux modal ── */
      'lm-title': 'Download for Linux',
      'lm-ver-label': 'Latest version:',
      'lm-deb-name': '.deb — Ubuntu / Debian',
      'lm-deb-desc': 'Recommended for Ubuntu, Debian, Linux Mint',
      'lm-rpm-name': '.rpm — Fedora / RHEL',
      'lm-rpm-desc': 'Recommended for Fedora, openSUSE, RHEL',
      'lm-img-name': '.AppImage — Universal',
      'lm-img-desc': 'Works on any Linux distro, no install needed',
      'lm-fallback-q': 'Not sure which to pick?',
      'lm-fallback-a': 'Browse all releases',
      'lm-back': 'Back',
      'lm-dl': 'Download',
      /* ── Support page ── */
      'sp-title': 'Support Center',
      'sp-desc': 'Need help with Munjez? Use one of the support channels below, then check quick fixes and FAQ.',
      'sp-contact-title': 'Contact options',
      'sp-contact-desc': 'Choose the fastest way based on your request.',
      'sp-btn-bug': 'Report a bug',
      'sp-btn-issues': 'View all issues',
      'sp-btn-email': 'Email support',
      'sp-tips-title': 'Before contacting support',
      'sp-tip1': 'Install the latest version and test again.',
      'sp-tip2': 'Include your OS version and what happened step by step.',
      'sp-tip3': 'Add a screenshot or short video when possible.',
      'sp-tip4': 'Mention whether the issue is always reproducible or random.',
      'sp-faq': 'Quick FAQ',
      'sp-q1': 'Does Munjez require an internet connection?',
      'sp-a1': 'Munjez is designed to be offline-first and works locally on your device. However, it connects to the internet for: checking for app updates, downloading additional ambient sounds on demand, authentication and cloud sync via Firebase (when signed in), fetching Hijri calendar and prayer time data via the Aladhan API, and real-time whiteboard collaboration. All core features work fully offline without signing in.',
      'sp-q2': 'Where is my data stored?',
      'sp-a2': 'All your data is stored locally in a SQLite database on your device. When you sign in, you can optionally enable cloud sync via Firebase, which stores a copy of your data on the cloud for cross-device access. On Windows, the local data folder is located at <code style="color:var(--accent);font-size:13px;background:rgba(124,58,237,.15);padding:2px 6px;border-radius:4px">%LOCALAPPDATA%\\com.osama.dev\\Munjez</code>.',
      'sp-q3': 'Will I lose my data if I update the app?',
      'sp-a3': 'No. Updates preserve your data automatically. The app creates a backup before any update to make sure nothing is lost.',
      'sp-q4': 'Why does Windows show a security warning when I install Munjez?',
      'sp-a4': 'Munjez is not yet signed with a paid code-signing certificate, so Windows SmartScreen flags it as an unrecognized app. This is normal for independent apps and does <strong>not</strong> mean the app is harmful. To proceed, click <strong>More info</strong> then <strong>Run anyway</strong>. Full step-by-step instructions are on the <a href="../windows-install/" style="color:var(--accent);text-decoration:none">installation guide page</a>.',
      'sp-q5': 'Which platforms does Munjez support?',
      'sp-a5': 'Munjez is available on Windows (10/11), Linux (AppImage, DEB, RPM), and Android (APK). It is also listed on the Microsoft Store.',
      'sp-q6': 'Does Munjez support Arabic and Hijri calendar?',
      'sp-a6': 'Yes. Munjez has full Arabic language support with right-to-left layout and a built-in Hijri calendar with all calendar views (Year, Month, Week, Day).',
      'sp-q7': 'What are desktop widgets and how do I use them?',
      'sp-a7': 'Munjez offers floating desktop widgets for focus timer, habits, calendar, countdown, and more. You can access them from the widget menu or the system tray. Widgets stay on top of other windows so you can track your progress while working.',
      'sp-q8': 'Can I customize keyboard shortcuts?',
      'sp-a8': 'Yes. Munjez supports custom keyboard shortcuts with macros — you can bind key combinations to perform multiple actions in sequence.',
      'sp-q9': 'How does the Focus Mode (Pomodoro) work?',
      'sp-a9': 'Focus Mode uses the Pomodoro technique with customizable work and break durations. It includes color-coded phases (red for focus, green for short breaks, orange for long breaks), desktop notifications, and an optional floating widget.',
      'sp-q10': 'Does Munjez have white noise or ambient sounds?',
      'sp-a10': 'Yes. Munjez includes a library of ambient sounds (rain, café, nature, and more) that you can mix together to create your ideal focus environment.',
      'sp-q11': 'How can I suggest a new feature?',
      'sp-a11': 'Open a GitHub issue and describe the feature, why it helps, and how you expect it to work.',
      'sp-q12': 'How long does a support response usually take?',
      'sp-a12': 'Response times vary, but tickets with clear reproduction steps and screenshots are handled faster.',
      /* ── Privacy Policy ── */
      'pp-title': 'Privacy Policy',
      'pp-updated': 'Last updated: June 27, 2026',
      'pp-overview-h': 'Overview',
      'pp-overview-p': 'Munjez is an offline-first productivity app available on Windows, Linux, and Android. It includes task management, habit tracking, calendar, notes, whiteboard, focus timer (Pomodoro), stopwatch, countdown, and customizable desktop widgets. We designed it to keep your data local whenever possible, with optional cloud features available when you choose to sign in.',
      'pp-data-h': 'Data We Collect',
      'pp-data-p': 'Munjez does not require account creation to use its core features. The app does not collect usage analytics or telemetry. When you use Munjez without signing in, no personal data is collected or transmitted.',
      'pp-account-h': 'Account & Authentication',
      'pp-account-p': 'You may optionally sign in using Google or email/password via Firebase Authentication. When you sign in, we receive and store the following information provided by your authentication provider:',
      'pp-account-1': 'Email address',
      'pp-account-2': 'Display name (if provided)',
      'pp-account-3': 'Profile photo URL (if provided by Google)',
      'pp-account-4': 'A unique user identifier (UID) generated by Firebase',
      'pp-account-p2': 'This information is used solely for authentication and enabling cloud sync. We do not share it with third parties or use it for advertising.',
      'pp-local-h': 'Local Data Storage',
      'pp-local-p': 'All your data — tasks, habits, calendar events, notes, whiteboard drawings, focus sessions, countdown timers, and app settings — is stored locally on your device in a SQLite database. Without signing in, nothing leaves your device. You are responsible for managing backups and device security.',
      'pp-sync-h': 'Cloud Sync',
      'pp-sync-p': 'When you sign in, Munjez offers optional cloud sync via Google Firebase (Firestore). Synced data may include tasks, folders, habits, countdowns, memories, notes, focus sessions, and stopwatch data. Sync uses a last-write-wins strategy and is encrypted in transit. You can control which data categories are synced from the app settings.',
      'pp-collab-h': 'Real-Time Collaboration',
      'pp-collab-p': 'The Whiteboard feature supports real-time collaboration. When you join a collaborative session, your drawing actions and cursor position are transmitted to other participants via a WebSocket server. No personal data beyond your display name is shared during collaboration sessions.',
      'pp-network-h': 'Network Connections',
      'pp-network-p': 'Munjez connects to the internet for the following purposes:',
      'pp-network-1': 'Checking for app updates via GitHub',
      'pp-network-2': 'Downloading additional ambient sounds on demand',
      'pp-network-3': 'Authentication and cloud sync via Firebase (when signed in)',
      'pp-network-4': 'Fetching Hijri calendar and prayer time data via the Aladhan API',
      'pp-network-5': 'Real-time whiteboard collaboration via WebSocket',
      'pp-network-p2': 'No usage analytics, telemetry, or tracking data is transmitted during any of these connections.',
      'pp-notifications-h': 'Notifications',
      'pp-notifications-p': 'Munjez may send local notifications for task reminders, habit reminders, sleep reminders, hourly chimes, and focus timer alerts. These notifications are processed entirely on your device and are never sent to any server.',
      'pp-files-h': 'File Access',
      'pp-files-p': 'Munjez may access your file system only when you explicitly choose to export or import data (e.g., saving a backup), attach images to memories or notes, or open whiteboard files (.munjez). The app does not scan, index, or access any files without your direct action.',
      'pp-delete-h': 'Account & Data Deletion',
      'pp-delete-p': 'You can delete your account at any time from the app settings. Deleting your account permanently removes all your cloud-synced data from Firebase, clears your local data, and deletes your authentication record. This action is irreversible.',
      'pp-crash-h': 'Crash Reports and Diagnostics',
      'pp-crash-p': 'Munjez does not automatically send crash reports, analytics, or diagnostics. Logs are stored locally on your device for debugging purposes and are never transmitted.',
      'pp-third-h': 'Third-Party Services',
      'pp-third-p': 'Munjez integrates with the following third-party services:',
      'pp-third-1': '<strong>Firebase Authentication & Firestore</strong> (Google) — for sign-in and cloud sync',
      'pp-third-2': '<strong>Firebase Storage</strong> (Google) — for storing user-uploaded content',
      'pp-third-3': '<strong>GitHub</strong> — for update checks and release downloads',
      'pp-third-4': '<strong>Aladhan API</strong> — for Hijri calendar and prayer time data',
      'pp-third-p2': 'These services are governed by their own privacy policies. We encourage you to review them.',
      'pp-children-h': "Children's Privacy",
      'pp-children-p': 'Munjez is suitable for all ages when used without signing in, as it collects no personal data in offline mode. If a child signs in, the authentication data described above will be collected. We recommend that children under 13 use the app with parental supervision, especially when using cloud features.',
      'pp-changes-h': 'Changes to This Policy',
      'pp-changes-p': 'We may update this Privacy Policy from time to time. Any changes will be reflected on this page with an updated date.',
      'pp-contact-h': 'Contact',
      'pp-contact-p': 'For privacy questions, contact us at <a class="mail" href="https://mail.google.com/mail/?view=cm&fs=1&to=munjezsupport@gmail.com" target="_blank" rel="noopener noreferrer">munjezsupport@gmail.com</a>.',
      /* ── Uninstall Feedback ── */
      'uf-title': 'Uninstall Feedback',
      'uf-desc': "We're sorry to see you go. Your feedback helps us improve Munjez for future versions.",
      'uf-reason-label': 'Main reason for uninstalling',
      'uf-placeholder': 'Select a reason',
      'uf-opt-placeholder': 'Select a reason',
      'uf-opt-bugs': 'Too many bugs',
      'uf-opt-missing': 'Missing features',
      'uf-opt-perf': 'Performance issues',
      'uf-opt-ui': 'UI/UX not suitable',
      'uf-opt-switch': 'Switching to another app',
      'uf-opt-other': 'Other',
      'uf-reason-error': 'Please select a reason before sending.',
      'uf-comeback-label': 'What could make you come back?',
      'uf-cb-perf': 'Better performance and lower memory usage',
      'uf-cb-mobile': 'Better mobile experience',
      'uf-cb-feat': 'More productivity features',
      'uf-details-label': 'Additional details',
      'uf-details-ph': 'Tell us what happened, what was missing, or what we should improve.',
      'uf-email-label': 'Email (optional)',
      'uf-send': 'Send feedback',
      'uf-email-direct': 'Email directly',
      'uf-note': 'This form sends feedback directly to: munjezsupport@gmail.com',
      'uf-done': 'Thanks for your feedback. We appreciate your time.',
      /* ── Terms of Service ── */
      'tos-title': 'Terms of Service',
      'tos-updated': 'Last updated: June 27, 2026',
      'tos-acceptance-h': 'Acceptance of Terms',
      'tos-acceptance-p': 'By downloading, installing, or using Munjez, you agree to be bound by these Terms of Service. If you do not agree, please do not use the app. These terms apply to all versions of Munjez, including Windows, Linux, and Android.',
      'tos-description-h': 'About Munjez',
      'tos-description-p': 'Munjez is a free, offline-first productivity desktop and mobile app. It includes task management, habit tracking, calendar, notes, whiteboard, focus timer (Pomodoro), stopwatch, countdown timers, and customizable desktop widgets. The app is developed and maintained by a single independent developer.',
      'tos-free-h': 'Free to Use',
      'tos-free-p': 'Munjez is provided free of charge. No subscription or payment is required. We reserve the right to introduce optional paid features in the future, but the core functionality will remain free.',
      'tos-account-h': 'Account & Sign-In',
      'tos-account-p': 'Munjez does not require an account to use its core features — all your data is stored locally on your device. Optional sign-in (via Google or email/password through Firebase Authentication) is available for features like cloud sync and cross-device access. By signing in, you authorize Munjez to access basic profile information from your chosen provider solely for authentication and sync purposes. You can delete your account and all associated cloud data at any time from the app settings.',
      'tos-data-h': 'Your Data',
      'tos-data-p': 'Your tasks, habits, notes, and other content belong to you. Munjez does not claim ownership over your data. All data is stored locally on your device in a SQLite database. When you sign in, you may enable cloud sync, which stores a copy of your data on Firebase servers to allow cross-device access. You are solely responsible for backing up your data. We are not liable for any data loss resulting from device failure, app uninstallation, operating system changes, or cloud service disruptions.',
      'tos-conduct-h': 'Acceptable Use',
      'tos-conduct-p': 'You agree to use Munjez only for lawful, personal productivity purposes. You must not:',
      'tos-conduct-1': 'Reverse engineer, decompile, or modify the app beyond what applicable law permits',
      'tos-conduct-2': 'Use the app to store or process illegal content',
      'tos-conduct-3': 'Attempt to exploit or disrupt the app\'s update or download infrastructure',
      'tos-conduct-4': 'Misrepresent the app or impersonate its developer',
      'tos-ip-h': 'Intellectual Property',
      'tos-ip-p': 'Munjez, its logo, design, and source code are the intellectual property of its developer. You may not copy, redistribute, or sell the app or any part of it without explicit written permission. The app name "Munjez" and its branding may not be used in a way that implies endorsement without permission.',
      'tos-updates-h': 'Updates & Availability',
      'tos-updates-p': 'We may release updates, add features, or remove features at any time without prior notice. We do not guarantee that the app will always be available, error-free, or continuously updated. The app may be discontinued at any time.',
      'tos-disclaimer-h': 'Disclaimer of Warranties',
      'tos-disclaimer-p': 'Munjez is provided "as is" without any warranty of any kind, express or implied. We do not warrant that the app will meet your specific requirements, be uninterrupted, or be free from bugs or errors. Your use of the app is at your own risk.',
      'tos-liability-h': 'Limitation of Liability',
      'tos-liability-p': 'To the fullest extent permitted by law, the developer of Munjez shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of or inability to use the app, including but not limited to data loss, lost productivity, or device damage.',
      'tos-collab-h': 'Collaboration Features',
      'tos-collab-p': 'The Whiteboard feature allows real-time collaboration with other users. When you join a collaborative session, your drawing actions are shared with other participants. You are responsible for the content you create and share during collaborative sessions. Do not share sensitive or confidential information through collaboration features.',
      'tos-thirdparty-h': 'Third-Party Services',
      'tos-thirdparty-p': 'Munjez relies on the following third-party services: GitHub for update delivery, Firebase (Authentication, Firestore, and Storage) for sign-in and cloud sync, and the Aladhan API for Hijri calendar data. These services are governed by their own terms and privacy policies. We are not responsible for the practices or availability of these third-party services.',
      'tos-changes-h': 'Changes to These Terms',
      'tos-changes-p': 'We may update these Terms of Service at any time. Continued use of the app after changes are posted constitutes your acceptance of the new terms. We will update the "Last updated" date at the top of this page when changes are made.',
      'tos-contact-h': 'Contact',
      'tos-contact-p': 'For any questions about these terms, contact us at <a class="mail" href="https://mail.google.com/mail/?view=cm&fs=1&to=munjezsupport@gmail.com" target="_blank" rel="noopener noreferrer">munjezsupport@gmail.com</a>.'
    },
    ar: {
      /* ── Shared ── */
      'back': 'الرئيسية',
      '404-title': 'الصفحة غير موجودة',
      '404-desc': 'الصفحة التي تبحث عنها غير موجودة أو تم نقلها.',
      '404-btn': 'العودة للرئيسية',
      /* ── Changelog ── */
      'cl-title': 'سجل <span>التحديثات</span>',
      'cl-desc': 'تاريخ التحديثات والميزات الجديدة والتحسينات في منجز.',
      'cl-footer': 'للاطلاع على القائمة الكاملة للإصدارات والتنزيلات، زُر <a href="https://github.com/Osama2214/munjez-releases/releases" target="_blank" rel="noopener noreferrer">إصدارات GitHub</a>.',
      'contact-support': 'تواصل مع الدعم',
      'support-cta': 'هل ما زلت تواجه مشكلة؟ فريق الدعم هنا للمساعدة.',
      /* ── Main nav ── */
      'nav-features': 'المميزات',
      'nav-screenshots': 'لقطات الشاشة',
      'nav-themes': 'السمات',
      'nav-support': 'الدعم',
      'nav-download': 'تنزيل',
      'nav-developer': 'المطور',
      'nav-dl': '',
      /* ── Hero ── */
      'hero-badge': 'تطبيق مجاني — ‏Windows‏ & ‏Linux‏ & ‏Android',
      'hero-sub': 'تطبيقك الشامل للإنتاجية',
      'hero-tagline': 'المهام والعادات وجلسات التركيز والملاحظات والسبورة والويدجات — كل شيء في تطبيق واحد <strong style="white-space:nowrap">يعمل بلا إنترنت</strong>. مصمَّم لمن يريد الإنجاز.',
      'hero-win': 'Windows',
      'hero-linux': 'Linux',
      'hero-android': 'Android',
      'win-store': 'Microsoft Store',
      'win-direct': 'تحميل مباشر',
      'android-apk': 'تحميل APK',
      'android-gplay': 'Google Play',
      'coming-soon': '(قريبًا)',
      'linux-download': 'تحميل',
      'linux-guide': 'دليل التثبيت',
      'feat-show-more': 'عرض المزيد',
      /* ── Features ── */
      'feat-label': 'المميزات',
      'feat-title': 'كل ما تحتاجه<br>لتبقى منتجاً',
      'feat-desc': '١٢ أداة قوية في تطبيق سطح مكتب سريع وأنيق — من المهام والعادات إلى الملاحظات والسبورة والويدجات العائمة.',
      'feat-tasks-title': 'إدارة مهام ذكية',
      'feat-tasks-desc': 'نظِّم مهامك في مجلدات بأولويات ومواعيد تسليم. أضف مهاماً متكررة وملاحظات صوتية وملفات وصور — كل التفاصيل في مكان واحد.',
      'feat-cal-title': 'تقويم متكامل',
      'feat-cal-desc': 'اعرض مهامك في طرق عرض سنوية وشهرية وأسبوعية ويومية. دعم كامل للتقويم الهجري مع جدولة المهام بالسحب والإفلات.',
      'feat-focus-title': 'وضع التركيز (Pomodoro)',
      'feat-focus-desc': 'حافظ على إنتاجيتك بجلسات تركيز وفترات راحة منظمة. ألوان مختلفة لكل مرحلة — أحمر للتركيز، وأخضر للاستراحة القصيرة، وبرتقالي للاستراحة الطويلة.',
      'feat-habits-title': 'متتبع العادات',
      'feat-habits-desc': 'كوِّن عادات يومية وتابع تقدمك بصرياً. سجِّل كل عادة يومياً وشاهد ثباتك يتطور مع الوقت.',
      'feat-stopwatch-title': 'ساعة إيقاف',
      'feat-stopwatch-desc': 'قِس الوقت بدقة. سجِّل اللفات والفترات وتابع جلساتك بواجهة نظيفة وخالية من المشتتات.',
      'feat-sounds-title': 'أصوات محيطة',
      'feat-sounds-desc': 'احجب المشتتات بمكتبة أصوات محيطة. امزج صوت المطر والمقهى والطبيعة وغيرها لإنشاء بيئة التركيز المثالية.',
      /* ── Feature tags ── */
      'tag-folders': 'مجلدات', 'tag-priorities': 'أولويات', 'tag-recurring': 'مهام متكررة',
      'tag-voice-notes': 'ملاحظات صوتية', 'tag-recycle-bin': 'سلة المهملات',
      'tag-4views': '٤ طرق عرض', 'tag-hijri': 'التقويم الهجري', 'tag-drag-drop': 'سحب وإفلات',
      'tag-pomodoro': 'مؤقت بومودورو', 'tag-color-phases': 'مراحل ملونة', 'tag-flip-clock': 'ساعة قلابة',
      'tag-daily-streaks': 'سلاسل يومية', 'tag-streak-cal': 'تقويم السلاسل', 'tag-color-tags': 'وسوم ملونة',
      'tag-lap-times': 'أوقات اللفات', 'tag-milliseconds': 'ميلي ثانية',
      'tag-rain': 'مطر', 'tag-cafe-noise': 'ضجيج مقهى', 'tag-nature': 'أصوات الطبيعة', 'tag-volume-mix': 'مزج الصوت',
      /* ── New feature cards ── */
      'feat-notes-title': 'الملاحظات',
      'feat-notes-desc': 'محرر نصوص غني لأفكارك. نظِّم ملاحظاتك في عرض شبكي أو قائمة أو عرض مقسَّم مع صور وتسجيلات صوتية وبطاقات ملونة.',
      'feat-memories-title': 'الذكريات واليوميات',
      'feat-memories-desc': 'وثِّق لحظات الحياة بيوميات مصورة. صنِّف وابحث وأعد زيارة ذكرياتك مرتبة حسب التاريخ مع تتبع الوقت المنقضي.',
      'feat-whiteboard-title': 'السبورة',
      'feat-whiteboard-desc': 'ارسم وخطط واعصف ذهنياً على لوحة لا نهائية. تعاون مع الآخرين لحظياً من خلال التحرير المتزامن.',
      'feat-countdown-title': 'مؤقت العد التنازلي',
      'feat-countdown-desc': 'اضبط عدّادات تنازلية للمواعيد والأحداث والأهداف. أدِر عدة مؤقتات معاً مع بطاقات تقدم مرئية وتنبيهات صوتية.',
      'feat-sync-title': 'المزامنة السحابية',
      'feat-sync-desc': 'سجِّل دخولك بحساب Google أو البريد الإلكتروني لمزامنة بياناتك بين أجهزتك عبر Firebase. مهامك وعاداتك وملاحظاتك وأكثر تبقى متزامنة — بأمان وفي الوقت الفعلي.',
      'feat-widgets-title': 'ويدجات سطح المكتب',
      'feat-widgets-desc': 'ثبِّت ويدجات عائمة على سطح مكتبك — مؤقت التركيز والمهام والعادات والتقويم والعد التنازلي وأكثر. مرئية دائماً وفوق كل النوافذ.',
      'tag-rich-editor': 'محرر غني', 'tag-grid-view': 'عرض شبكي', 'tag-voice-recordings': 'تسجيلات صوتية', 'tag-tags': 'وسوم',
      'tag-photo-journal': 'يوميات مصورة', 'tag-date-tracking': 'تتبع التاريخ', 'tag-search': 'بحث',
      'tag-drawing': 'رسم', 'tag-collaboration': 'تعاون لحظي', 'tag-diagrams': 'مخططات',
      'tag-cross-device': 'بين الأجهزة', 'tag-firebase': 'Firebase', 'tag-realtime-sync': 'لحظي', 'tag-optional': 'اختياري',
      'tag-multiple-timers': 'مؤقتات متعددة', 'tag-audio-alerts': 'تنبيهات صوتية', 'tag-progress-cards': 'بطاقات تقدم',
      'tag-floating': 'عائمة', 'tag-always-on-top': 'فوق النوافذ', 'tag-11-widgets': '+١١ ويدجت',
      /* ── Screenshots ── */
      'ss-label': 'لقطات الشاشة',
      'ss-title': 'شاهده أثناء العمل',
      'ss-desc': 'استعرض كل ميزة من خلال لقطات شاشة حقيقية من التطبيق.',
      'tab-tasks': 'المهام',
      'tab-cal': 'التقويم',
      'tab-habits': 'العادات',
      'tab-focus': 'التركيز',
      'tab-stopwatch': 'ساعة الإيقاف',
      'tab-notes': 'الملاحظات',
      'tab-memories': 'الذكريات',
      'tab-whiteboard': 'السبورة',
      'tab-countdown': 'العد التنازلي',
      'tab-widgets': 'الودجات',
      /* ── Focus section ── */
      'focus-label': 'وضع التركيز',
      'focus-title': 'لكل مرحلة<br>طاقتها الخاصة',
      'focus-desc': 'جلسات Pomodoro ملوَّنة تضعك في الذهنية المناسبة لكل لحظة من يوم عملك.',
      'focus-time': 'وقت التركيز',
      'focus-time-desc': 'وضع العمل العميق — ابقَ مركّزاً',
      'short-break': 'استراحة قصيرة',
      'short-break-desc': 'راحة سريعة — ابتعد قليلاً عن الشاشة',
      'long-break': 'استراحة طويلة',
      'long-break-desc': 'استحققتها — أعِد شحنك بالكامل',
      /* ── Themes ── */
      'themes-label': 'السمات',
      'themes-title': 'اجعله على ذوقك',
      'themes-desc': 'بدِّل بين سمات جميلة تتناسب مع مزاجك وأسلوب عملك.',
      /* ── Support (home) ── */
      'sup-label': 'الدعم',
      'sup-title': 'هل تحتاج مساعدة؟<br>نحن هنا',
      'sup-desc': 'أبلِغ عن مشكلة، اقترح ميزة، أو تواصل معنا إذا لم يعمل التطبيق بشكل صحيح.',
      'sup-main-title': 'تواصل مع فريق Munjez',
      'sup-main-desc': 'إذا اكتشفت خللاً أو لديك اقتراح ميزة، افتح تذكرة على GitHub وأضف لقطة شاشة إن أمكن. نراجع المشكلات بانتظام ونحدد الأولويات بحسب الأثر.',
      'sup-btn-bug': 'الإبلاغ عن خلل',
      'sup-btn-issues': 'عرض جميع المشكلات',
      'sup-btn-email': 'مراسلة الدعم',
      'sup-more': 'فتح مركز الدعم الكامل',
      'sup-tips-title': 'قبل الإبلاغ، تذكر',
      'sup-tip1': '<strong>حدِّث أولاً:</strong> ثبِّت أحدث إصدار وأعد المحاولة.',
      'sup-tip2': '<strong>شارك السياق:</strong> أذكر نظام التشغيل وإصداره وما كنت تفعله.',
      'sup-tip3': '<strong>أضف وسائط:</strong> أرفق لقطة شاشة أو مقطعاً قصيراً لتسريع الحل.',
      /* ── Download (home) ── */
      'dl-label': 'تنزيل',
      'dl-title': 'مستعد للبدء؟<br><span>أنجز أهدافك</span>',
      'dl-desc': 'مجاني وسريع ويعمل بالكامل بلا إنترنت. بلا حساب. بلا اشتراك. أنت وأهدافك فقط.',
      'dl-win': 'Windows',
      'dl-win-sub': 'Microsoft Store',
      'dl-linux': 'Linux',
      'dl-linux-sub': 'AppImage · DEB · RPM',
      'dl-android': 'Android',
      'dl-android-sub': 'تحميل APK',
      'dl-no-account': 'لا حاجة لحساب',
      'dl-offline': 'يعمل بلا إنترنت',
      'dl-free': 'مجاني للأبد',
      'dl-count-label': 'تنزيل حتى الآن',
      /* ── Footer ── */
      'footer-privacy': 'سياسة الخصوصية',
      'footer-support': 'مركز الدعم',
      'footer-changelog': 'سجل التحديثات',
      'dev-label': 'تعرّف على المطوّر',
      'dev-name': 'أسامة أحمد',
      'dev-role': 'مطوّر وصانع منجز',
      'dev-bio': 'شغوف ببناء أدوات تساعد الناس على الإنجاز. منجز بدأ كمشروع شخصي وتحوّل لتطبيق إنتاجية متكامل — مصمَّم ومبني بالكامل بواسطة مطوّر واحد.',
      /* ── Windows install ── */
      'win-dl-started': 'بدأ التنزيل!',
      'win-hero-title': 'تثبيت <span>Munjez</span> على Windows',
      'win-hero-desc': 'إذا لم يبدأ المتصفح التنزيل تلقائياً، انقر فوق الزر أدناه. بعد اكتمال التنزيل، شغِّل ملف التثبيت.',
      'win-dl-btn': 'تنزيل مرة أخرى',
      'win-warn': 'إذا أظهر Windows تحذيراً أمنياً — إليك كيفية التعامل معه',
      'win-sc1': 'المتصفح أوقف التنزيل',
      'win-sc2': 'ظهور تحذير SmartScreen',
      'win-sc3': 'الملف محظور — لا يمكن تشغيله',
      'win-sc1-s1': 'في <strong>Chrome</strong>: افتح شريط التنزيلات ← انقر فوق <strong>⋮</strong> بجانب الملف ← <strong>Keep</strong>',
      'win-sc1-s2': 'تظهر رسالة تأكيد ثانية — انقر فوق <strong>Keep anyway</strong>',
      'win-sc1-s3': 'في <strong>Edge</strong>: انقر فوق <strong>...</strong> ← <strong>Keep</strong> ← <strong>Show more</strong> ← <strong>Keep anyway</strong>',
      'win-sc1-s4': 'شغِّل ملف التثبيت — قد يظهر تحذير SmartScreen، اتبع <strong>الحالة 2</strong> أدناه',
      'win-sc2-s1': 'انقر فوق <strong>More info</strong>',
      'win-sc2-s2': 'انقر فوق <strong>Run anyway</strong>',
      'win-sc3-s1': 'انقر بزر الماوس الأيمن فوق الملف ← <strong>Show more options</strong>',
      'win-sc3-s2': 'انقر فوق <strong>Properties</strong>',
      'win-sc3-s3': 'ضع علامة في <strong>Unblock</strong> ← انقر فوق <strong>OK</strong>',
      'win-sc3-s4': 'شغِّل ملف التثبيت مرة أخرى',
      /* ── Linux install ── */
      'lx-title-pre': 'تثبيت',
      'lx-title-mid': 'على Linux —',
      'lx-dl-started': 'بدأ التنزيل!',
      'lx-hero-desc': 'إذا لم يبدأ المتصفح التنزيل تلقائياً، انقر فوق الزر أدناه.',
      'lx-dl-btn': 'تنزيل مرة أخرى',
      'lx-hint1': 'نزِّل الملف بالنقر فوق الزر أعلاه',
      'lx-hint2': 'انقر بزر الماوس الأيمن فوق مجلد التنزيلات ← <span>Open Terminal Here</span>',
      'lx-hint3': 'شغِّل أمر التثبيت أدناه',
      'lx-install': 'خطوات التثبيت',
      'lx-trouble': 'حل المشكلات',
      /* ── Linux modal ── */
      'lm-title': 'تنزيل لـ Linux',
      'lm-ver-label': 'أحدث إصدار:',
      'lm-deb-name': '.deb — Ubuntu / Debian',
      'lm-deb-desc': 'موصى به لـ Ubuntu وDebian وLinux Mint',
      'lm-rpm-name': '.rpm — Fedora / RHEL',
      'lm-rpm-desc': 'موصى به لـ Fedora وopenSUSE وRHEL',
      'lm-img-name': '.AppImage — Universal',
      'lm-img-desc': 'يعمل على أي توزيعة Linux، لا يحتاج تثبيتاً',
      'lm-fallback-q': 'لست متأكداً من الاختيار؟',
      'lm-fallback-a': 'تصفح جميع الإصدارات',
      'lm-back': 'رجوع',
      'lm-dl': 'تنزيل',
      /* ── Support page ── */
      'sp-title': 'مركز الدعم',
      'sp-desc': 'هل تحتاج مساعدة مع Munjez؟ استخدم إحدى قنوات الدعم أدناه، ثم راجع الحلول السريعة والأسئلة الشائعة.',
      'sp-contact-title': 'خيارات التواصل',
      'sp-contact-desc': 'اختر الطريقة الأسرع بحسب طلبك.',
      'sp-btn-bug': 'الإبلاغ عن خلل',
      'sp-btn-issues': 'عرض جميع المشكلات',
      'sp-btn-email': 'مراسلة الدعم',
      'sp-tips-title': 'قبل التواصل مع الدعم',
      'sp-tip1': 'ثبِّت أحدث إصدار وأعد المحاولة.',
      'sp-tip2': 'أذكر نظام التشغيل وإصداره وما حدث خطوة بخطوة.',
      'sp-tip3': 'أضف لقطة شاشة أو مقطع فيديو قصير إن أمكن.',
      'sp-tip4': 'وضِّح إذا كانت المشكلة تحدث دائماً أم بصورة عشوائية.',
      'sp-faq': 'الأسئلة الشائعة',
      'sp-q1': 'هل يتطلب Munjez اتصالاً بالإنترنت؟',
      'sp-a1': 'Munjez مصمَّم للعمل بلا إنترنت ويخزِّن بياناتك محلياً على جهازك. لكنه يتصل بالإنترنت لعدة أغراض: التحقق من تحديثات التطبيق، تنزيل أصوات محيطية إضافية عند الطلب، المصادقة والمزامنة السحابية عبر Firebase (عند تسجيل الدخول)، جلب بيانات التقويم الهجري ومواقيت الصلاة عبر Aladhan API، والتعاون المباشر على السبورة البيضاء. جميع الميزات الأساسية تعمل بالكامل بدون إنترنت وبدون تسجيل دخول.',
      'sp-q2': 'أين تُخزَّن بياناتي؟',
      'sp-a2': 'جميع بياناتك تُخزَّن محلياً في قاعدة بيانات SQLite على جهازك. عند تسجيل الدخول، يمكنك تفعيل المزامنة السحابية عبر Firebase، مما يحفظ نسخة من بياناتك على السحابة للوصول من أجهزة متعددة. على Windows، مجلد البيانات المحلي موجود في <code style="color:var(--accent);font-size:13px;background:rgba(124,58,237,.15);padding:2px 6px;border-radius:4px">%LOCALAPPDATA%\\com.osama.dev\\Munjez</code>.',
      'sp-q3': 'هل سأفقد بياناتي عند تحديث التطبيق؟',
      'sp-a3': 'لا. التحديثات تحافظ على بياناتك تلقائياً. التطبيق ينشئ نسخة احتياطية قبل أي تحديث للتأكد من عدم فقدان أي شيء.',
      'sp-q4': 'لماذا يظهر Windows تحذيراً عند تثبيت Munjez؟',
      'sp-a4': 'Munjez لم يُوقَّع بعد بشهادة توقيع رمز مدفوعة، لذا يصنِّفه SmartScreen تطبيقاً غير معروف. هذا أمر طبيعي للتطبيقات المستقلة ولا يعني أن التطبيق ضار. للمتابعة، انقر فوق <strong>More info</strong> ثم <strong>Run anyway</strong>. التعليمات الكاملة متوفرة في <a href="../windows-install/" style="color:var(--accent);text-decoration:none">صفحة دليل التثبيت</a>.',
      'sp-q5': 'ما المنصات التي يدعمها Munjez؟',
      'sp-a5': 'Munjez متاح على Windows (10/11) وLinux (AppImage, DEB, RPM) وAndroid (APK). كما أنه متوفر على متجر Microsoft.',
      'sp-q6': 'هل يدعم Munjez اللغة العربية والتقويم الهجري؟',
      'sp-a6': 'نعم. Munjez يدعم اللغة العربية بالكامل مع واجهة من اليمين لليسار وتقويم هجري مدمج بجميع العروض (سنوي، شهري، أسبوعي، يومي).',
      'sp-q7': 'ما هي ودجات سطح المكتب وكيف أستخدمها؟',
      'sp-a7': 'يقدم Munjez ودجات سطح مكتب عائمة لمؤقت التركيز والعادات والتقويم والعد التنازلي والمزيد. يمكنك الوصول إليها من قائمة الودجات أو شريط النظام. الودجات تبقى فوق النوافذ الأخرى حتى تتمكن من متابعة تقدمك أثناء العمل.',
      'sp-q8': 'هل يمكنني تخصيص اختصارات لوحة المفاتيح؟',
      'sp-a8': 'نعم. يدعم Munjez اختصارات لوحة مفاتيح مخصصة مع ماكرو — يمكنك ربط مجموعات مفاتيح لتنفيذ إجراءات متعددة بالتسلسل.',
      'sp-q9': 'كيف يعمل وضع التركيز (بومودورو)؟',
      'sp-a9': 'وضع التركيز يستخدم تقنية بومودورو مع فترات عمل واستراحة قابلة للتخصيص. يشمل مراحل ملونة (أحمر للتركيز، أخضر للاستراحة القصيرة، برتقالي للاستراحة الطويلة)، إشعارات سطح المكتب، وودجت عائم اختياري.',
      'sp-q10': 'هل يحتوي Munjez على ضوضاء بيضاء أو أصوات محيطية؟',
      'sp-a10': 'نعم. يتضمن Munjez مكتبة من الأصوات المحيطية (مطر، مقهى، طبيعة، والمزيد) التي يمكنك مزجها معاً لإنشاء بيئة التركيز المثالية لك.',
      'sp-q11': 'كيف أقترح ميزة جديدة؟',
      'sp-a11': 'افتح تذكرة على GitHub وصِف الميزة — سبب أهميتها وكيف تتوقع أن تعمل.',
      'sp-q12': 'كم يستغرق الرد على الدعم عادةً؟',
      'sp-a12': 'تتفاوت أوقات الرد، لكن التذاكر ذات الخطوات التفصيلية ولقطات الشاشة تُعالَج بشكل أسرع.',
      /* ── Privacy Policy ── */
      'pp-title': 'سياسة الخصوصية',
      'pp-updated': 'آخر تحديث: 27 يونيو 2026',
      'pp-overview-h': 'نظرة عامة',
      'pp-overview-p': 'Munjez تطبيق إنتاجية يعمل بلا إنترنت ومتاح على Windows وLinux وAndroid. يشمل إدارة المهام، تتبع العادات، التقويم، الملاحظات، السبورة البيضاء، مؤقت التركيز (بومودورو)، ساعة الإيقاف، العد التنازلي، وودجات سطح المكتب. صممناه ليبقي بياناتك محلية على جهازك قدر الإمكان، مع ميزات سحابية اختيارية عند تسجيل الدخول.',
      'pp-data-h': 'البيانات التي نجمعها',
      'pp-data-p': 'لا يتطلب Munjez إنشاء حساب لاستخدام وظائفه الأساسية. التطبيق لا يجمع تحليلات استخدام أو بيانات قياس عن بُعد. عند استخدام Munjez بدون تسجيل الدخول، لا تُجمَع أو تُنقَل أي بيانات شخصية.',
      'pp-account-h': 'الحساب والمصادقة',
      'pp-account-p': 'يمكنك اختيارياً تسجيل الدخول باستخدام Google أو البريد الإلكتروني/كلمة المرور عبر Firebase Authentication. عند تسجيل الدخول، نستقبل ونخزّن المعلومات التالية من مزوّد المصادقة:',
      'pp-account-1': 'البريد الإلكتروني',
      'pp-account-2': 'الاسم المعروض (إن وُجد)',
      'pp-account-3': 'رابط صورة الملف الشخصي (إن وُجد عبر Google)',
      'pp-account-4': 'معرّف مستخدم فريد (UID) يُنشئه Firebase',
      'pp-account-p2': 'تُستخدم هذه المعلومات فقط للمصادقة وتفعيل المزامنة السحابية. لا نشاركها مع أطراف خارجية ولا نستخدمها للإعلانات.',
      'pp-local-h': 'تخزين البيانات محلياً',
      'pp-local-p': 'جميع بياناتك — المهام والعادات وأحداث التقويم والملاحظات ورسومات السبورة وجلسات التركيز ومؤقتات العد التنازلي وإعدادات التطبيق — تُخزَّن محلياً على جهازك في قاعدة بيانات SQLite. بدون تسجيل الدخول، لا تغادر أي بيانات جهازك. أنت المسؤول عن إدارة النسخ الاحتياطية وتأمين جهازك.',
      'pp-sync-h': 'المزامنة السحابية',
      'pp-sync-p': 'عند تسجيل الدخول، يوفر Munjez مزامنة سحابية اختيارية عبر Google Firebase (Firestore). قد تشمل البيانات المُزامَنة المهام والمجلدات والعادات والعد التنازلي والذكريات والملاحظات وجلسات التركيز وبيانات ساعة الإيقاف. تستخدم المزامنة استراتيجية الكتابة الأخيرة تفوز وتكون مشفرة أثناء النقل. يمكنك التحكم في فئات البيانات المُزامَنة من إعدادات التطبيق.',
      'pp-collab-h': 'التعاون اللحظي',
      'pp-collab-p': 'تدعم ميزة السبورة التعاون اللحظي. عند انضمامك لجلسة تعاونية، تُنقَل إجراءات الرسم وموقع المؤشر إلى المشاركين الآخرين عبر خادم WebSocket. لا تُشارَك أي بيانات شخصية بخلاف اسمك المعروض أثناء جلسات التعاون.',
      'pp-network-h': 'الاتصال بالإنترنت',
      'pp-network-p': 'يتصل Munjez بالإنترنت للأغراض التالية:',
      'pp-network-1': 'التحقق من تحديثات التطبيق عبر GitHub',
      'pp-network-2': 'تنزيل أصوات محيطية إضافية عند الطلب',
      'pp-network-3': 'المصادقة والمزامنة السحابية عبر Firebase (عند تسجيل الدخول)',
      'pp-network-4': 'جلب بيانات التقويم الهجري وأوقات الصلاة عبر Aladhan API',
      'pp-network-5': 'التعاون اللحظي على السبورة عبر WebSocket',
      'pp-network-p2': 'لا تُنقَل أي تحليلات استخدام أو بيانات قياس عن بُعد أو بيانات تتبع أثناء أي من هذه الاتصالات.',
      'pp-notifications-h': 'الإشعارات',
      'pp-notifications-p': 'قد يُرسِل Munjez إشعارات محلية لتذكيرات المهام والعادات وتذكير النوم والتنبيه كل ساعة ومنبهات مؤقت التركيز. تتم معالجة هذه الإشعارات بالكامل على جهازك ولا تُرسَل أبداً إلى أي خادم.',
      'pp-files-h': 'الوصول للملفات',
      'pp-files-p': 'قد يصل Munjez إلى نظام الملفات فقط عندما تختار صراحةً تصدير أو استيراد البيانات (مثل حفظ نسخة احتياطية)، أو إرفاق صور بالذكريات أو الملاحظات، أو فتح ملفات السبورة (.munjez). التطبيق لا يفحص أو يفهرس أو يصل إلى أي ملفات بدون إجراء مباشر منك.',
      'pp-delete-h': 'حذف الحساب والبيانات',
      'pp-delete-p': 'يمكنك حذف حسابك في أي وقت من إعدادات التطبيق. حذف حسابك يزيل نهائياً جميع بياناتك المُزامَنة من Firebase، ويمسح بياناتك المحلية، ويحذف سجل المصادقة الخاص بك. هذا الإجراء لا يمكن التراجع عنه.',
      'pp-crash-h': 'تقارير الأعطال والتشخيص',
      'pp-crash-p': 'لا يُرسِل Munjez تقارير أعطال أو تحليلات أو تقارير تشخيصية تلقائياً. تُخزَّن السجلات محلياً على جهازك لأغراض تصحيح الأخطاء ولا تُنقَل أبداً.',
      'pp-third-h': 'خدمات الأطراف الخارجية',
      'pp-third-p': 'يتكامل Munjez مع خدمات الأطراف الخارجية التالية:',
      'pp-third-1': '<strong>Firebase Authentication و Firestore</strong> (Google) — لتسجيل الدخول والمزامنة السحابية',
      'pp-third-2': '<strong>Firebase Storage</strong> (Google) — لتخزين المحتوى المرفوع من المستخدم',
      'pp-third-3': '<strong>GitHub</strong> — للتحقق من التحديثات وتنزيل الإصدارات',
      'pp-third-4': '<strong>Aladhan API</strong> — لبيانات التقويم الهجري وأوقات الصلاة',
      'pp-third-p2': 'تخضع هذه الخدمات لسياسات خصوصيتها الخاصة. ننصحك بمراجعتها.',
      'pp-children-h': 'خصوصية الأطفال',
      'pp-children-p': 'Munjez مناسب لجميع الأعمار عند الاستخدام بدون تسجيل الدخول، حيث لا يجمع أي بيانات شخصية في وضع عدم الاتصال. إذا سجّل طفل دخوله، ستُجمَع بيانات المصادقة المذكورة أعلاه. ننصح بإشراف الوالدين للأطفال دون سن 13 عاماً، خاصة عند استخدام الميزات السحابية.',
      'pp-changes-h': 'التغييرات على هذه السياسة',
      'pp-changes-p': 'قد نحدِّث هذه السياسة من وقت لآخر. ستنعكس أي تغييرات على هذه الصفحة مع تحديث التاريخ.',
      'pp-contact-h': 'تواصل معنا',
      'pp-contact-p': 'لأي استفسار يتعلق بالخصوصية، تواصل معنا على <a class=\"mail\" href=\"https://mail.google.com/mail/?view=cm&fs=1&to=munjezsupport@gmail.com\" target=\"_blank\" rel=\"noopener noreferrer\">munjezsupport@gmail.com</a>.',
      /* ── Theme Names ── */
      'theme-dark': 'الثيم الداكن',
      'theme-midnight': 'ثيم منتصف الليل',
      'theme-ocean': 'ثيم المحيط',
      'theme-lilac': 'الثيم البنفسجي',
      'theme-iris': 'ثيم الزهور',
      'theme-coast': 'الثيم الساحلي',
      'theme-light': 'الثيم الفاتح',
      'theme-blush': 'ثيم الوردي الناعم',
      'theme-rose': 'ثيم الورد',
      'theme-olive': 'ثيم الزيتوني',
      'theme-earth': 'الثيم الترابي',
      'theme-cocoa': 'ثيم الكاكاو',
      'theme-mint': 'ثيم النعناع',
      'theme-ember': 'الثيم الناري',
      /* ── Uninstall Feedback ── */
      'uf-title': 'تقييم إلغاء التثبيت',
      'uf-desc': 'نأسف لمغادرتك. تقييمك يساعدنا على تحسين Munjez في الإصدارات القادمة.',
      'uf-reason-label': 'السبب الرئيسي لإلغاء التثبيت',
      'uf-placeholder': 'اختر سبباً',
      'uf-opt-placeholder': 'اختر سبباً',
      'uf-opt-bugs': 'أخطاء كثيرة',
      'uf-opt-missing': 'ميزات مفقودة',
      'uf-opt-perf': 'مشاكل في الأداء',
      'uf-opt-ui': 'الواجهة غير مناسبة',
      'uf-opt-switch': 'الانتقال لتطبيق آخر',
      'uf-opt-other': 'أخرى',
      'uf-reason-error': 'يرجى اختيار سبب قبل الإرسال.',
      'uf-comeback-label': 'ما الذي قد يجعلك تعود؟',
      'uf-cb-perf': 'أداء أفضل واستهلاك أقل للذاكرة',
      'uf-cb-mobile': 'تجربة موبايل أفضل',
      'uf-cb-feat': 'ميزات إنتاجية أكثر',
      'uf-details-label': 'تفاصيل إضافية',
      'uf-details-ph': 'أخبرنا بما حدث، أو ما كان ناقصاً، أو ما يجب تحسينه.',
      'uf-email-label': 'البريد الإلكتروني (اختياري)',
      'uf-send': 'إرسال التقييم',
      'uf-email-direct': 'مراسلة مباشرة',
      'uf-note': 'يُرسل هذا النموذج تقييمك مباشرةً إلى: munjezsupport@gmail.com',
      'uf-done': 'شكراً على تقييمك. نقدّر وقتك.',
      /* ── شروط الاستخدام ── */
      'tos-title': 'شروط الاستخدام',
      'tos-updated': 'آخر تحديث: 27 يونيو 2026',
      'tos-acceptance-h': 'قبول الشروط',
      'tos-acceptance-p': 'بتنزيلك أو تثبيتك أو استخدامك لـ Munjez، فإنك توافق على الالتزام بشروط الاستخدام هذه. إذا كنت لا توافق، يُرجى عدم استخدام التطبيق. تنطبق هذه الشروط على جميع إصدارات Munjez بما فيها Windows وLinux وAndroid.',
      'tos-description-h': 'عن Munjez',
      'tos-description-p': 'Munjez تطبيق إنتاجية مجاني يعمل بلا إنترنت، متاح على سطح المكتب والموبايل. يشمل إدارة المهام، تتبع العادات، التقويم، الملاحظات، السبورة، مؤقت التركيز (بومودورو)، ساعة الإيقاف، العد التنازلي، وودجات سطح مكتب قابلة للتخصيص. التطبيق مطوَّر ومدار بواسطة مطوّر مستقل واحد.',
      'tos-free-h': 'مجاني للاستخدام',
      'tos-free-p': 'Munjez مقدَّم مجاناً بالكامل. لا يتطلب اشتراكاً أو دفعاً. نحتفظ بحق تقديم ميزات اختيارية مدفوعة في المستقبل، لكن الوظائف الأساسية ستبقى مجانية.',
      'tos-account-h': 'الحساب وتسجيل الدخول',
      'tos-account-p': 'لا يتطلب Munjez حساباً لاستخدام وظائفه الأساسية — جميع بياناتك تُخزَّن محلياً على جهازك. يتوفر تسجيل دخول اختياري (عبر Google أو البريد الإلكتروني/كلمة المرور من خلال Firebase Authentication) لميزات كالمزامنة السحابية والوصول عبر أجهزة متعددة. بتسجيل دخولك، تمنح Munjez إذناً للوصول إلى معلومات ملفك الشخصي الأساسية من الجهة المختارة لأغراض المصادقة والمزامنة. يمكنك حذف حسابك وجميع البيانات السحابية المرتبطة به في أي وقت من إعدادات التطبيق.',
      'tos-data-h': 'بياناتك',
      'tos-data-p': 'مهامك وعاداتك وملاحظاتك وسائر محتواك ملكٌ لك. لا يدّعي Munjez أي ملكية على بياناتك. جميع البيانات تُخزَّن محلياً على جهازك في قاعدة بيانات SQLite. عند تسجيل الدخول، يمكنك تفعيل المزامنة السحابية التي تخزّن نسخة من بياناتك على خوادم Firebase للسماح بالوصول عبر أجهزة متعددة. أنت المسؤول الوحيد عن إنشاء نسخ احتياطية. لسنا مسؤولين عن أي فقدان للبيانات ناتج عن عطل الجهاز أو إلغاء تثبيت التطبيق أو تغييرات نظام التشغيل أو انقطاع الخدمات السحابية.',
      'tos-conduct-h': 'الاستخدام المقبول',
      'tos-conduct-p': 'توافق على استخدام Munjez لأغراض إنتاجية شخصية ومشروعة فقط. يُحظر عليك:',
      'tos-conduct-1': 'إجراء هندسة عكسية أو فك تشفير أو تعديل التطبيق بما يتجاوز ما يسمح به القانون المعمول به',
      'tos-conduct-2': 'استخدام التطبيق لتخزين أو معالجة محتوى غير قانوني',
      'tos-conduct-3': 'محاولة استغلال أو تعطيل بنية تحديث التطبيق أو تنزيله',
      'tos-conduct-4': 'تحريف التطبيق أو انتحال شخصية مطوّره',
      'tos-ip-h': 'الملكية الفكرية',
      'tos-ip-p': 'Munjez وشعاره وتصميمه وكوده المصدري هي ملكية فكرية لمطوّره. لا يجوز نسخ التطبيق أو إعادة توزيعه أو بيعه أو أي جزء منه دون إذن كتابي صريح. لا يجوز استخدام اسم "Munjez" أو هويته البصرية بطريقة توحي بالتأييد دون إذن.',
      'tos-updates-h': 'التحديثات والتوفر',
      'tos-updates-p': 'قد نُصدِر تحديثات أو نضيف ميزات أو نحذفها في أي وقت دون إشعار مسبق. لا نضمن أن يكون التطبيق متاحاً دائماً أو خالياً من الأخطاء أو مستمراً في التحديث. قد يتوقف التطبيق في أي وقت.',
      'tos-disclaimer-h': 'إخلاء مسؤولية الضمانات',
      'tos-disclaimer-p': 'يُقدَّم Munjez "كما هو" دون أي ضمان من أي نوع، صريحاً أو ضمنياً. لا نضمن أن التطبيق سيلبي متطلباتك المحددة، أو سيعمل دون انقطاع، أو سيكون خالياً من الأخطاء. استخدامك للتطبيق على مسؤوليتك الخاصة.',
      'tos-liability-h': 'تحديد المسؤولية',
      'tos-liability-p': 'إلى أقصى حد يسمح به القانون، لن يكون مطوّر Munjez مسؤولاً عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية تنشأ عن استخدامك للتطبيق أو عدم قدرتك على استخدامه، بما في ذلك على سبيل المثال فقدان البيانات أو فقدان الإنتاجية أو تلف الجهاز.',
      'tos-collab-h': 'ميزات التعاون',
      'tos-collab-p': 'تتيح ميزة السبورة التعاون اللحظي مع مستخدمين آخرين. عند انضمامك لجلسة تعاونية، تُشارَك إجراءات الرسم مع المشاركين الآخرين. أنت المسؤول عن المحتوى الذي تنشئه وتشاركه أثناء جلسات التعاون. لا تشارك معلومات حساسة أو سرية عبر ميزات التعاون.',
      'tos-thirdparty-h': 'خدمات الأطراف الخارجية',
      'tos-thirdparty-p': 'يعتمد Munjez على خدمات الأطراف الخارجية التالية: GitHub لتوصيل التحديثات، Firebase (المصادقة وFirestore وStorage) لتسجيل الدخول والمزامنة السحابية، وAladhan API لبيانات التقويم الهجري. تخضع هذه الخدمات لشروطها وسياسات خصوصيتها الخاصة. لسنا مسؤولين عن ممارسات أو توفر هذه الخدمات.',
      'tos-changes-h': 'التغييرات على هذه الشروط',
      'tos-changes-p': 'قد نحدِّث شروط الاستخدام هذه في أي وقت. استمرارك في استخدام التطبيق بعد نشر التغييرات يُعدّ قبولاً للشروط الجديدة. سنحدِّث تاريخ "آخر تحديث" في أعلى هذه الصفحة عند إجراء أي تغييرات.',
      'tos-contact-h': 'تواصل معنا',
      'tos-contact-p': 'لأي استفسار حول هذه الشروط، تواصل معنا على <a class="mail" href="https://mail.google.com/mail/?view=cm&fs=1&to=munjezsupport@gmail.com" target="_blank" rel="noopener noreferrer">munjezsupport@gmail.com</a>.'
    }
  };

  function t(key) {
    return T[lang] && T[lang][key] !== undefined ? T[lang][key] : (T.en[key] !== undefined ? T.en[key] : key);
  }

  function apply() {
    var isAr = lang === 'ar';
    document.documentElement.lang = lang;
    document.documentElement.dir = isAr ? 'rtl' : 'ltr';
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var v = t(el.getAttribute('data-i18n'));
      if (!v) return;
      if (v.indexOf('<') !== -1) { el.innerHTML = v; } else { el.textContent = v; }
    });
    document.querySelectorAll('[data-i18n-ph]').forEach(function (el) {
      var v = t(el.getAttribute('data-i18n-ph'));
      if (v) el.placeholder = v;
    });
    // Translate theme names
    var themeKeyMap = {
      'Dark Theme': 'theme-dark',
      'Midnight Theme': 'theme-midnight',
      'Ocean Theme': 'theme-ocean',
      'Lilac Theme': 'theme-lilac',
      'Iris Theme': 'theme-iris',
      'Coast Theme': 'theme-coast',
      'Light Theme': 'theme-light',
      'Blush Theme': 'theme-blush',
      'Rose Theme': 'theme-rose',
      'Olive Theme': 'theme-olive',
      'Earth Theme': 'theme-earth',
      'Cocoa Theme': 'theme-cocoa',
      'Mint Theme': 'theme-mint',
      'Ember Theme': 'theme-ember'
    };
    document.querySelectorAll('.theme-name').forEach(function(el) {
      var orig = el.getAttribute('data-theme-en') || el.textContent.trim();
      if (!el.getAttribute('data-theme-en')) el.setAttribute('data-theme-en', orig);
      var key = themeKeyMap[orig];
      if (key) {
        var translated = T[lang] && T[lang][key];
        el.textContent = translated ? translated : orig;
      }
    });
    if (isAr) { loadArabicFont(); } else { document.body.style.fontFamily = ''; }
    var btn = document.getElementById('lang-toggle');
    if (btn) { btn.textContent = isAr ? 'EN' : 'AR'; }
  }

  function loadArabicFont() {
    if (!document.getElementById('ar-font')) {
      var l = document.createElement('link');
      l.id = 'ar-font';
      l.rel = 'stylesheet';
      l.href = 'https://fonts.googleapis.com/css2?family=Almarai:wght@400;700;800&display=swap';
      document.head.appendChild(l);
    }
    document.body.style.fontFamily = '"Almarai", system-ui, sans-serif';
  }

  function toggle() {
    lang = lang === 'en' ? 'ar' : 'en';
    localStorage.setItem(KEY, lang);
    apply();
    setTimeout(function(){ document.dispatchEvent(new Event('langchange')); }, 0);
  }

  function init() {
    var btn = document.getElementById('lang-toggle');
    if (btn) { btn.onclick = toggle; }
    if (lang !== 'en') {
      apply();
      setTimeout(function(){ document.dispatchEvent(new Event('langchange')); }, 0);
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

  window.LANG = { t: t, lang: function () { return lang; } };
})();